apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
  namespace: '{{{M3_NAMESPACE}}}'
  labels:
    project: '{{{M3_PROJECT}}}'
    environment: '{{{M3_ENVIRONMENT}}}'
    componenet: '{{{M3_COMPONENET}}}'
    application: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
    version: '{{{M3_VERSION}}}'
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  rules:
    - host: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}.m3ntorship.net'
      http:
        paths:
          - backend:
              serviceName: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
              servicePort: 80
            path: /
    - host: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}.m3ntorship.tech'
      http:
        paths:
          - backend:
              serviceName: '{{{M3_PROJECT}}}-{{{M3_COMPONENET}}}-{{{M3_ENVIRONMENT}}}'
              servicePort: 80
            path: /
